### ISSUE TITLE
Op een invoice wordt een configurable product + de simple weergegeven ipv alleen de config met de gekozen opties

### ISSUE THREAD

**Issue by Nielex** [dealer4dealer/magento2-substituteorders#11]
Environment:

- Magento 2.3.1
- Alleen dealer4dealer/magento2-substituteorders geinstalleerd
- 1 Configurable product aangemaakt (Sweater) met 2 opties (Yellow + Black)

Verwacht:

Hetzelfde resultaat op de invoice als in de backend van Magento:
![Screenshot 2019-04-02 at 13 47 19](https://user-images.githubusercontent.com/5550238/55400331-e12a4f80-554d-11e9-9c0f-d7d7e3105dc2.png)

Resultaat:

Zowel het configurable product als de simple worden weergegeven op de invoice:
![Screenshot 2019-04-02 at 13 48 46](https://user-images.githubusercontent.com/5550238/55400394-1171ee00-554e-11e9-85eb-f6270aefe7aa.png)

**Comment by doldersma** [comment]
Opgelost in release 1.0.13
