### ISSUE TITLE
Bijlagen worden gecached

### ISSUE THREAD

**Issue by doldersma** [dealer4dealer/magento2-substituteorders#17]
Bijlagen worden gecached op een verkeerde manier.     
Hierdoor zijn ze een 2e keer niet te downloaden.

**Comment by experius-nl** [comment]
Wij hebben dit issue op te lossen door in [Controller/Attachment/Download.php](https://github.com/dealer4dealer/magento2-substituteorders/blob/master/Controller/Attachment/Download.php) de volgende wijzigingen door te voeren (vanaf regel 48):

`$this->fileFactory->create(
                $fileName,
                [
                    'type' => 'filename',
                    'value' => $filePath
                ],
                DirectoryList::MEDIA,
                'application/octet-stream',
                ''
            )->setHeader(
                'Cache-Control',
                'must-revalidate, post-check=0, pre-check=0',
                true
            );`

Dit zet simpelweg de cache vat attachments uit.

**Comment by doldersma** [comment]
bedankt voor de tip, heb het aangepast.
