### ISSUE TITLE
Admin grid error in 2.3.3

### ISSUE THREAD

**Issue by rubenexp** [dealer4dealer/magento2-substituteorders#21]
In Magento 2.3.3 komt de volgende error naar voren in de admin order grid van de module: 
`Class argument is invalid: Magento\Framework\View\Element\UiComponent\Context`

Dit komt door de volgende regels https://github.com/dealer4dealer/magento2-substituteorders/blob/master/view/adminhtml/ui_component/dealer4dealer_order_index.xml#L3-L6

We hebben (tot nu toe) ondervonden dat deze zonder gevolgen verwijderd kunnen worden, ook voor 2.2.x.

**Comment by doldersma** [comment]
Dank voor de melding, doorgevoerd op de master branch.
