### ISSUE TITLE
Error can't be translated, because of product name in message

### ISSUE THREAD

**Issue by pstuifzand** [dealer4dealer/magento2-substituteorders#41]
On this line https://github.com/dealer4dealer/magento2-substituteorders/blob/009492983be69f4b030a37b0015527134de353f0/Controller/Order/Reorder.php#L143
the error can't be translated, because of the product name in de message. You would need a translation for every product name.

This is the patch we use to fix this.

```php
$errors[] = __("We can\'t add %1 to your shopping cart right now.", $product->getName());
```

**Comment by doldersma** [comment]
Hi, thank you for pointing this out, we will apply this patch in version 1.0.27. 
Also in the same file on line 188.
