### ISSUE TITLE
Original/additional logic on orders etc. isn't working anymore

### ISSUE THREAD

**Issue by ArjenMiedema** [dealer4dealer/magento2-substituteorders#46]
With this module a lot of logic related to the original Magento\Sales module doesn't work properly anymore, because all the controllers, models, views and blocks are rewritten/overwritten.

In my opinion it would be better if this module adds logic to the original \Magento\Sales logic (i.e. import external orders into the original Magento orders) instead of rewriting all the extisting logic.

I understand why the attachments are separated, but the orders, invoices and shipments make things more difficult to extend. For example using Adobe Commerce (with B2B) doesn't work anymore, unless you create an extra module that  makes this possible, but that shouldn't be needed in my opinion.

What's the reason why this approach was taken and not adding logic?

**Comment by JKingma** [comment]
@doldersma do you know?

**Comment by doldersma** [comment]
@JKingma please create a support ticket for this in our Zendesk environment.
