### ISSUE TITLE
Orderhistorie geeft HTTP ERROR 500 pagina

### ISSUE THREAD

**Issue by Timothy-V** [dealer4dealer/magento2-substituteorders#7]
Wanneer een klant frontend via zijn Account dashboard naar 'Order history' gaat, komt hij op een niet-werkende HTTP ERROR 500 pagina.

![image](https://user-images.githubusercontent.com/47175711/52064778-9607b680-2575-11e9-9f84-08634f54c853.png)

![image](https://user-images.githubusercontent.com/47175711/52056732-4d470200-2563-11e9-9e2f-59b9e82c9deb.png)

**Comment by Timothy-V** [comment]
Fatal error: Uncaught Error: Call to a member function getValue() on null in /data/web/magento2/vendor/dealer4dealer/module-substituteorders/Block/Order/History.php:131 Stack trace: #0 /data/web/magento2/vendor/dealer4dealer/module-substituteorders/Block/Order/History.php(68): Dealer4Dealer\SubstituteOrders\Block\Order\History->getOrderCollection() #1 /data/web/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(272): Dealer4Dealer\SubstituteOrders\Block\Order\History->_prepareLayout() #2 /data/web/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(150): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor)) #3 /data/web/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #4 /data/web/magento2/vendor/magento/framework/View/Layout.php(343): Magento\Framework\View\L in /data/web/magento2/vendor/dealer4dealer/module-substituteorders/Block/Order/History.php on line 131

**Comment by doldersma** [comment]
Issue reproduceerbaar en opgelost in 1.0.11
